# Generated by Django 5.2.8 on 2026-02-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='building_type',
            field=models.CharField(choices=[('ACADEMIC', 'Academic Block'), ('HOSTEL', 'Hostel'), ('CANTEEN', 'Canteen'), ('LIBRARY', 'Library'), ('ADMIN', 'Administrative Block')], default='ACADEMIC', max_length=20),
        ),
    ]
