# Generated by Django 5.2.8 on 2026-02-14 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_building_building_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_phase', models.CharField(choices=[('CLASS_HOURS', 'Class Hours'), ('SHORT_BREAK', 'Short Break'), ('LUNCH_BREAK', 'Lunch Break'), ('ACTIVITIES', 'Activities'), ('NIGHT', 'Night')], max_length=20)),
                ('expected_percentage', models.IntegerField(help_text='Expected occupancy percentage for this phase')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.building')),
            ],
            options={
                'unique_together': {('building', 'time_phase')},
            },
        ),
    ]
