# Generated by Django 5.2.8 on 2026-02-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_phaseoccupancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_type',
            field=models.CharField(choices=[('ACADEMIC', 'Academic Block'), ('LAB', 'Laboratory'), ('HOSTEL', 'Hostel'), ('CANTEEN', 'Canteen'), ('LIBRARY', 'Library'), ('ADMIN', 'Administrative Block'), ('SHOP', 'Shops'), ('AUDITORIUM', 'Auditorium')], default='ACADEMIC', max_length=20),
        ),
    ]
