# Generated by Django 6.0.2 on 2026-02-14 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_building_building_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.time(23, 59)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='building_type',
            field=models.CharField(choices=[('ACADEMIC', 'Academic Block'), ('HOSTEL', 'Hostel'), ('CANTEEN', 'Canteen'), ('LIBRARY', 'Library'), ('ADMIN', 'Administrative Block'), ('SHOP', 'Shops'), ('AUDITORIUM', 'Auditorium')], default='ACADEMIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='phaseoccupancy',
            name='time_phase',
            field=models.CharField(choices=[('CLASS_HOURS', 'Class Hours'), ('SHORT_BREAK', 'Short Break'), ('LUNCH_BREAK', 'Lunch Break'), ('ACTIVITIES', 'Activities'), ('OFF_HOURS', 'Off Hours'), ('NIGHT', 'Night')], max_length=20),
        ),
    ]
