# Generated by Django 6.0.2 on 2026-03-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('EXAM', 'Exam'), ('PLACEMENT', 'Placement Drive'), ('PTA', 'PTA Meeting'), ('ADMISSION', 'Admission Process'), ('TECHFEST', 'Techfest'), ('SEMINAR', 'Seminar'), ('CULTURAL', 'Cultural Event'), ('SPORTS', 'Sports Event')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='building',
            name='occupancy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='phaseoccupancy',
            name='time_phase',
            field=models.CharField(choices=[('CLASS_HOURS', 'Class Hours'), ('SHORT_BREAK', 'Short Break'), ('LUNCH_BREAK', 'Lunch Break'), ('ACTIVITIES', 'Activities'), ('OFF_HOURS', 'Off Hours')], max_length=20),
        ),
    ]
