# Generated by Django 6.0.2 on 2026-03-13 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_event_event_type_alter_building_occupancy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='occupancy',
        ),
        migrations.AddField(
            model_name='building',
            name='is_navigational_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='multi_location_events', to='dashboard.building'),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_type',
            field=models.CharField(blank=True, choices=[('ACADEMIC', 'Academic Block'), ('HOSTEL', 'Hostel'), ('CANTEEN', 'Canteen'), ('LIBRARY', 'Library'), ('ADMIN', 'Administrative Block'), ('SHOP', 'Shops'), ('AUDITORIUM', 'Auditorium'), ('MAIN_GATE', 'Main Gate')], default='ACADEMIC', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('EXAM', 'Exam'), ('PLACEMENT', 'Placement Drive'), ('PTA', 'PTA Meeting'), ('ADMISSION', 'Admission')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dashboard.building'),
        ),
        migrations.AlterField(
            model_name='phaseoccupancy',
            name='expected_percentage',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='EnergyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('COLLEGE', 'Whole College'), ('BUILDING', 'Individual Building')], default='COLLEGE', max_length=20)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('energy_consumed_kwh', models.FloatField()),
                ('peak_demand_kw', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='energy_consumption_records', to='dashboard.building')),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('direction_hint', models.TextField()),
                ('from_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths_from', to='dashboard.building')),
                ('to_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths_to', to='dashboard.building')),
            ],
        ),
    ]
